# Generated by Django 3.2.4 on 2022-09-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webzine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('fake_tatile', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('writer', models.CharField(max_length=10)),
                ('writer_info', models.TextField()),
                ('cdate', models.DateTimeField()),
                ('open_date', models.DateTimeField()),
                ('isVisible', models.CharField(default='true', max_length=10)),
            ],
        ),
    ]
