# Generated by Django 3.2.4 on 2022-09-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webzine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blind_Webzine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blind_title', models.CharField(max_length=30)),
                ('blind_writer', models.CharField(max_length=10)),
                ('cdate', models.DateTimeField()),
                ('open_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='webzine',
            name='isVisible',
        ),
    ]
