# Generated by Django 3.2.4 on 2022-09-24 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webzine', '0002_auto_20220924_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webzine',
            name='fake_tatile',
        ),
    ]
