# Generated by Django 3.2.4 on 2022-09-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webzine', '0003_remove_webzine_fake_tatile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blind_webzine',
            name='cdate',
        ),
        migrations.RemoveField(
            model_name='blind_webzine',
            name='open_date',
        ),
    ]
