# Generated by Django 3.2.4 on 2022-09-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webzine', '0004_auto_20220924_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='blind_webzine',
            name='webzine_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webzine.webzine'),
        ),
    ]
