# Generated by Django 3.2.4 on 2022-09-25 02:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webzine', '0005_blind_webzine_webzine_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blind_webzine',
            name='webzine_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blinds', to='webzine.webzine'),
        ),
        migrations.AlterField(
            model_name='webzine',
            name='cdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
