# Generated by Django 4.0.4 on 2022-06-22 14:44

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proceeding',
            field=models.CharField(choices=[('진행중', '진행중'), ('마감', '마감'), ('진행예정', '진행예정')], default='진행중', max_length=10),
        ),
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
