# Generated by Django 3.2.4 on 2021-10-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
            ],
        ),
    ]
