# Generated by Django 3.2.4 on 2021-10-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream_list', '0002_keyword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
