# Generated by Django 4.0.4 on 2022-04-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream_list', '0003_delete_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='isVisible',
            field=models.CharField(default='true', max_length=10),
        ),
    ]
